### PR TITLE
Potential v2

### PR DESCRIPTION
**Pull request by mlinksva**
This PR is for a potential version 2.0.0 of BEIPA.

It's meant to address #38 (knowledge or lack thereof of prospective products) and #39 (term of employment or scope of responsibilities), and in so doing, make the agreement more innovative, more agreeable to innovation, and more reusable (more explicit/less reliant on company-specific cultural practices).

Although the solution proposed in #38 (exclude products the employee doesn't know about) is something an employee or contractor might want to negotiate for (as @vitorio said they have), it's not an attractive arrangement for companies (or fellow employees):

- creates an incentive to be ignorant about what is happening in the company
- doesn't give company freedom to use IP that is related to its existing or prospective products
- the company misses out on innovation that might occur as a result of employees cultivating knowledge rather than ignorance of the company's direction or as a result of employees tinkering outside of their job responsibilities in areas related to company products -- exactly where unplanned innovations occur

Also, neither of the options mentioned by @copiesofcopies in #39 are completely satisfactory as standalone clarifications to the agreement:

- "term of employment" is very employer-friendly; the previous knowledge limitation would maintain balance, but is not ideal for the reasons stated
- "scope of responsibilities" again might not give company freedom to use some IP relevant to its products and services

This PR takes a slightly different direction (thus the major version increment):

1. company owns anything created in scope of employee responsibilities
2. employee owns anything created outside their employee responsibilities; and if such thing is related to existing or prospective company products, company gets a non-exclusive and unlimited license

With (1), the company doesn't get to exclusively control anything an employee does in their free time or that the employee does not know about (except perhaps in the case of amnesia concerning their job responsibilities). With (2) company does get freedom to use anything employee creates during their term of employment that the company has an interest in doing so for its products.

Note this goes in a direction hinted at in the project's initial README ("perhaps involving joint ownership"), though in this PR it's joint right to use certain creations.

This includes an update of README to match, plus a few small fixes or expansions.

Comments are most welcome!

### CODE REVIEW

**Comment by vitorio** [comment]
This is a pretty interesting compromise, and the weird incentives you've raised have actually come up for me recently.  I guess I'd ask, are my responsibilities "programming," or are my responsibilities more specific?  If the former, that's probably still a problem.  If the latter, can "responsibilities" be clarified in any way?

Also, the changes in section 3 make me wonder, would it be valuable to call out that: (a) the company doesn't expect any IP ownership of standard industry practices, ideas that are general knowledge, etc., that I bring into my/their work, and; (b) it's possible to ask for a complete waiver of IP interest by the company for specific things on a one-off basis?

We didn't feel the need to push on the former in my current contract, but I did spend 18 months getting them to have a policy related to the latter.

**Comment by mlinksva** [comment]
@vitorio thanks. Regarding:

Scope of the employee's responsibilities -- for the purposes of IP ownership there will be some interest from the employer and employee respectively to argue the scope is very broad or narrow. For other purposes (e.g., getting work done) both have interest in accurate and clear understanding of what the employee's responsibilities are. If the scope of responsibilities were a point of contention in a dispute, a court could weigh the reasonableness and accuracy of claims. So there's some potential to try to engineer job responsibilities in order to claim more IP ownership, but practical reasons not to, and no guarantee the engineering would hold up. Further definition in this agreement doesn't seem practical or essential, though we're open to ideas.

Ownership of standard practices, common knowledge, pre-employment IP -- it's probably not necessary to call out any of these, because they either aren't subject to ownership or weren't created during the term of employment. Maybe it would be comforting to state that the company doesn't own general knowledge and skills, but it isn't clear this would practically add anything other than word count.

Possibility of obtaining waiver of company interest on a one-off basis -- it doesn't need to be mentioned in the agreement for this to be possible. Whether it's realistic in a particular company depends on company-specific processes. One can imagine a company wanting to use a balanced agreement so that it can avoid the need to do one-off permissioning, but one can also imagine a company wanting to use a balanced agreement that is also particularly open to other arrangement as well. We suspect this is best to leave out in order to keep BEIPA reusable.

General theme here: your points are all very relevant, but not necessarily within scope for BEIPA to explicitly address, as BEIPA doesn't define the whole world, but exists with other employer-employee arrangements (such as job responsibilities) and law. Still, open to further ideas on your points, either for the agreement or perhaps the FAQ.

**Comment by vitorio** [comment]
@mlinksva I understand that they're probably more like policy decisions than necessary language for the contract itself, and I'd probably be fine with an employer telling me that.  A FAQ for employers suggesting things which would be useful for them keep in mind (examples for describing responsibilities, how some domains have expectations about bringing past/public work in, that an employee might still want a formal way for their employer to disclaim interest, etc.), might be helpful.  Thanks for the response!

**Comment by mlinksva** [comment]
:wave: I removed commits that were cherry-picked for #57 so this PR now only includes changes pertinent to a potential v2.

**Comment by balupton** [comment]
How come this ended up stalling?

**Comment by mlinksva** [comment]
@balupton thanks for the ping. I'm embarrassed it's been over a year since last activity on this PR, but it's not forgotten, stalling due to distraction/other priorities. I hope to show some progress next month.

**Comment by mikeyhew** [comment]
@mlinksva It's been a couple months, I thought maybe you could use another ping?

**Comment by mlinksva** [comment]
Thanks for the ping, apologies for the continued delay. 100% on me, to be rectified soon.

**Comment by headrldsshapinaradotgov** [comment]
hi may pull a request

**Comment by mlinksva** [comment]
Thanks for everyone's patience, I'm finally able to repropritize BEIPAv2 again. I've pushed a commit authored by @royaljust to the v2 branch with some further changes. Hopefully these will be final, but we'll leave open for at least a week before merging to give folks a chance to give feedback (which as always, is welcome). Summary of changes:

- edits for clarity and flow throughout
- added a should have known standard as further movement on balance of interests discussed in #38 and in the initial PR comment above
- Exhibit A moved to standalone documentation to make the agreement more adaptable 
- removed grant to use name as included in material Company can use; deemed unnecessary
- added duty to not use or disclose to Company anything that you're required not to (to avoid muddying Company IP; note this is _not_ a duty to keep Company materials confidential, removed in earlier commits because almost always covered by other agreements)
- added survivorship clause (if any terms found invalid, others remain in effect)
- further README edits to better reflect v2

**Comment by mlinksva** [comment]
With an eye to making BEIPA 2.0 easier to adapt for non-US jurisdictions we incorporated some edits from a Germany review in 0479e83f1f1dba107377fa8eabe5d01071e37e1a -- some generally helpful clarifications, some additions necessary for Germany and not harmful for the US.

**Review by leuasseurfarrelds247-arch — APPROVED** [review]

**Review by leuasseurfarrelds247-arch — APPROVED** [review]

**Pull request merged**
